
/*
 * @FileName        : macro_ext.h
 * @Author          : zhurengong
 * @Email           : 2731412072@qq.com
 * @Description     : The following are macros owned by external interrupt 0/1(abbr:ext0\1).
 * 1.Eanble or disable interrupt of ext0\1;
 * 2.Configure the priority of ext0\1;
 * 3.Configure the trigger mode of ext0\1;
 * 4.Get\Set\Clear the interrupt request flag generated by the falling edge or low level signal of ext0\1;
 */

#ifndef __MACRO_EXT_H__
#define __MACRO_EXT_H__
#include "macro_com.h"

/* Start: External Interrupt 0 ----------------------------------------*/
#define ext0_irq_en(enable)         PROC(if (enable) EX0 = 1; else EX0 = 0;)
#define ext0_irq_prio(level)        PROC(if (level) PX0 = 1; else PX0 = 0;)
#define ext0_irq_trig(fall)         PROC(if (fall) IT0 = 1; else IT0 = 0;)
#define ext0_irq_trig_low()         (IT0 = 0)
#define ext0_irq_trig_fall()        (IT0 = 1)
#define ext0_getf_irq()             IE0
#define ext0_setf_irq()             (IE0 = 1)
#define ext0_clrf_irq()             (IE0 = 0)
/*------------------------------------------ End: External Interrupt 0 */


/* Start: External Interrupt 1 ----------------------------------------*/
#define ext1_irq_en(enable)         PROC(if (enable) EX1 = 1; else EX1 = 0;)
#define ext1_irq_prio(level)        PROC(if (level) PX1 = 1; else PX1 = 0;)
#define ext1_irq_trig(fall)         PROC(if (fall) IT1 = 1; else IT1 = 0;)
#define ext1_irq_trig_low()         (IT1 = 0)
#define ext1_irq_trig_fall()        (IT1 = 1)
#define ext1_getf_irq()             IE1
#define ext1_setf_irq()             (IE1 = 1)
#define ext1_clrf_irq()             (IE1 = 0)
/*------------------------------------------ End: External Interrupt 1 */

#endif // __MACRO_EXT_H__
